version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: darshan2580
      MYSQL_DATABASE: salessavvy
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sales-savvy-app:
    image: sales-savvy-app
    container_name: sales_savvy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/salessavvy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: darshan2580
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties

volumes:
  mysql_data: